const STORAGE_KEY='marginalia-language-bank-v1';
const categoryNames={recurring:'刊物常用表达',curious:'陌生但感兴趣',unexpected:'熟词生用'};
const samples=[
 {id:'sample-1',expression:'weather the storm',context:'The company may be better placed than its rivals to weather the storm.',source:'The Economist',article:'The resilience premium',location:'p. 58',category:'recurring',meaning:'挺过难关，经受住冲击。这里强调在不利环境中存活下来，而非消除问题。',note:'weather 作动词。常见搭配：weather a crisis / downturn / storm。',example:'Small independent shops need loyal customers to weather the slowdown.',status:'Practised',createdAt:'2026-09-22',nextReview:0,reviews:2},
 {id:'sample-2',expression:'savage',context:'The episode has savaged the government’s reputation for competence.',source:'The Economist',article:'A crisis of confidence',location:'paragraph 4',category:'unexpected',meaning:'v. 严重损害；猛烈攻击。比 damage 更有暴烈、无情的感觉。',note:'熟悉的形容词在这里作动词。可用于 reputation, industry, economy。',example:'Months of uncertainty have savaged the team’s morale.',status:'Noticed',createdAt:'2026-09-25',nextReview:0,reviews:0},
 {id:'sample-3',expression:'the uninitiated',context:'To the uninitiated, the ritual can look needlessly elaborate.',source:'The New Yorker',article:'The quiet ceremony of craft',location:'opening',category:'unexpected',meaning:'不了解门道的人；门外汉。带一点从圈内向圈外看的意味。',note:'the + adjective → 一类人。语气比 beginners 更正式，也更有观察者视角。',example:'To the uninitiated, the grading system can seem arbitrary.',status:'Active',createdAt:'2026-09-18',nextReview:0,reviews:5}
];
let entries=loadEntries(),currentStatus='all',reviewMode='meaning',reviewIndex=0,reviewDeck=[],revealed=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadEntries(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:samples}catch{return samples}}
function saveEntries(){localStorage.setItem(STORAGE_KEY,JSON.stringify(entries));updateMetrics()}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='bank')renderEntries();if(name==='recycle')startReview();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#todayDate').textContent=new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date());
function updateMetrics(){const count=s=>entries.filter(e=>e.status===s).length;$('#bankCount').textContent=`${entries.length} entries`;$('#activeCount').textContent=count('Active');$('#practiceCount').textContent=count('Practised');$('#noticedCount').textContent=count('Noticed');$('#dueCount').textContent=`${entries.filter(e=>!e.nextReview||e.nextReview<=Date.now()).length} due`}
function openEntry(entry=null,source=null){$('#entryForm').reset();$('#entryId').value=entry?.id||'';$('#dialogTitle').textContent=entry?'Edit expression':'Collect an expression';['expression','context','article','location','meaning','note','example','status','category','source'].forEach(k=>{if(entry&&entry[k]!=null)$(`#${k}`).value=entry[k]});if(!entry&&source)$('#source').value=source;$('#entryDialog').showModal();setTimeout(()=>$('#expression').focus(),50)}
$('#quickAddBtn').onclick=()=>openEntry();$('#addEntryBtn').onclick=()=>openEntry();
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#entryId').value||`entry-${Date.now()}`;const existing=entries.find(x=>x.id===id);const data={id,...Object.fromEntries(['expression','context','source','article','location','category','meaning','note','example','status'].map(k=>[k,$(`#${k}`).value.trim()])),createdAt:existing?.createdAt||new Date().toISOString().slice(0,10),nextReview:existing?.nextReview||0,reviews:existing?.reviews||0};if(existing)entries=entries.map(x=>x.id===id?data:x);else entries.unshift(data);saveEntries();$('#entryDialog').close();renderEntries();toast(existing?'Entry updated':'Saved to Language Bank')});
function renderEntries(){const q=$('#searchInput').value.toLowerCase(),cat=$('#categoryFilter').value;const filtered=entries.filter(e=>(currentStatus==='all'||e.status===currentStatus)&&(cat==='all'||e.category===cat)&&[e.expression,e.context,e.source,e.article,e.meaning,e.note].join(' ').toLowerCase().includes(q));$('#entryList').innerHTML=filtered.map(e=>`<article class="entry-row" data-id="${escapeHtml(e.id)}" tabindex="0"><div class="entry-expression"><b>${escapeHtml(e.expression)}</b><small>${escapeHtml(e.context||e.meaning)}</small></div><div class="entry-source"><b>${escapeHtml(e.source)}</b><small>${escapeHtml(e.article||e.location||'')}</small></div><span class="category-chip">${categoryNames[e.category]||''}</span><span class="status-pill ${e.status}">${e.status}</span><button class="row-menu" aria-label="查看 ${escapeHtml(e.expression)}">›</button></article>`).join('');$('#emptyState').hidden=filtered.length>0;$$('.entry-row').forEach(r=>{r.onclick=()=>showDetail(r.dataset.id);r.onkeydown=e=>{if(e.key==='Enter')showDetail(r.dataset.id)}})}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showDetail(id){const e=entries.find(x=>x.id===id);if(!e)return;$('#detailContent').innerHTML=`<div class="detail-head"><div><p>${escapeHtml(e.source)} · ${escapeHtml(e.article||'Untitled')} ${e.location?'· '+escapeHtml(e.location):''}</p><h2>${escapeHtml(e.expression)}</h2><span class="status-pill ${e.status}">${e.status}</span></div><button class="close-button" aria-label="关闭">×</button></div>${[['Original context',e.context],['Contextual meaning / 双语释义',e.meaning],['Mini note',e.note],['My sentence',e.example]].filter(x=>x[1]).map(x=>`<div class="detail-section"><label>${x[0]}</label><p>${escapeHtml(x[1])}</p></div>`).join('')}<div class="detail-actions"><button class="danger-button" data-delete>Delete</button><button class="primary-button" data-edit>Edit entry</button></div>`;const d=$('#detailDialog');d.querySelector('.close-button').onclick=()=>d.close();d.querySelector('[data-edit]').onclick=()=>{d.close();openEntry(e)};d.querySelector('[data-delete]').onclick=()=>{if(confirm(`Delete “${e.expression}”?`)){entries=entries.filter(x=>x.id!==id);saveEntries();d.close();renderEntries();toast('Entry deleted')}};d.showModal()}
$('#searchInput').addEventListener('input',renderEntries);$('#categoryFilter').onchange=renderEntries;$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentStatus=b.dataset.status;renderEntries()});
function startReview(){reviewDeck=entries.filter(e=>!e.nextReview||e.nextReview<=Date.now());if(!reviewDeck.length)reviewDeck=[...entries];reviewIndex=0;$('#reviewEmpty').hidden=reviewDeck.length>0;$('#reviewStage').hidden=!reviewDeck.length;renderReview()}
function renderReview(){if(!reviewDeck.length)return;revealed=false;const e=reviewDeck[reviewIndex];$('#reviewCounter').textContent=`${reviewIndex+1} / ${reviewDeck.length}`;$('#reviewBar').style.width=`${reviewIndex/reviewDeck.length*100}%`;$('#reviewSource').textContent=e.source;$('#reviewCategory').textContent=categoryNames[e.category];let context=escapeHtml(e.context||'Recall the expression and its meaning.');if(reviewMode==='expression'&&e.expression){const safe=escapeHtml(e.expression).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');context=context.replace(new RegExp(safe,'ig'),'<mark>hidden expression</mark>')}$('#reviewContext').innerHTML=context;$('#hiddenAnswer').hidden=false;$('#revealedAnswer').hidden=true;$('#reviewActions').hidden=true;$('#revealBtn').hidden=false;$('#revealedAnswer').innerHTML=reviewMode==='meaning'?`<h3>${escapeHtml(e.expression)}</h3><p>${escapeHtml(e.meaning)}</p>`:`<h3>${escapeHtml(e.expression)}</h3><p>${escapeHtml(e.meaning)}</p>`}
function reveal(){revealed=true;$('#hiddenAnswer').hidden=true;$('#revealedAnswer').hidden=false;$('#reviewActions').hidden=false;$('#revealBtn').hidden=true}
$('#hiddenAnswer').onclick=reveal;$('#revealBtn').onclick=reveal;$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');reviewMode=b.dataset.mode;renderReview()});
$$('[data-grade]').forEach(b=>b.onclick=()=>{const e=reviewDeck[reviewIndex],grade=b.dataset.grade,days=grade==='again'?0:grade==='hard'?2:7;e.reviews=(e.reviews||0)+1;e.nextReview=Date.now()+days*86400000;if(grade==='good'&&e.status==='Noticed')e.status='Practised';else if(grade==='good'&&e.status==='Practised'&&e.reviews>=3)e.status='Active';saveEntries();reviewIndex++;if(reviewIndex>=reviewDeck.length){$('#reviewBar').style.width='100%';$('#reviewStage').hidden=true;$('#reviewEmpty').hidden=false;$('#reviewEmpty h2').textContent='Review complete.';$('#reviewEmpty p').textContent=`You recycled ${reviewDeck.length} expression${reviewDeck.length===1?'':'s'} today.`}else renderReview()});
$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),entries},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`marginalia-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported')};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text()),incoming=Array.isArray(data)?data:data.entries;if(!Array.isArray(incoming))throw Error();const map=new Map(entries.map(x=>[x.id,x]));incoming.forEach(x=>map.set(x.id,x));entries=[...map.values()];saveEntries();renderEntries();$('#settingsDialog').close();toast(`Imported ${incoming.length} entries`)}catch{toast('Could not read this backup')}e.target.value=''};
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;ctx.registerTool({name:'collect_expression',title:'Collect expression',description:'Add a noticed English word or expression to the visible Language Bank.',inputSchema:{type:'object',properties:{expression:{type:'string'},meaning:{type:'string'},context:{type:'string'},source:{type:'string'},category:{type:'string',enum:['recurring','curious','unexpected']}},required:['expression','meaning'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input?.expression||!input?.meaning)throw new Error('expression and meaning are required');const entry={id:`entry-${Date.now()}`,expression:input.expression,meaning:input.meaning,context:input.context||'',source:input.source||'Other',article:'',location:'',category:input.category||'curious',note:'',example:'',status:'Noticed',createdAt:new Date().toISOString().slice(0,10),nextReview:0,reviews:0};entries.unshift(entry);saveEntries();renderEntries();return {id:entry.id,status:'saved'}}})}
updateMetrics();renderEntries();registerWebMCP();
$$('.lesson-tab').forEach(b=>b.onclick=()=>showLesson(b.dataset.lesson));$$('[data-next-lesson]').forEach(b=>b.onclick=()=>showLesson(b.dataset.nextLesson));
function showLesson(name){$$('.lesson-tab').forEach(b=>b.classList.toggle('active',b.dataset.lesson===name));$$('.lesson-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));document.querySelector('.lesson-path').scrollIntoView({behavior:'smooth',block:'start'})}
$$('.collect-lesson').forEach(b=>b.onclick=()=>{openEntry({id:'',expression:b.dataset.expression,context:b.dataset.context,source:'The Economist',article:'Can Germany’s recovery outrun the AfD?',location:'Guided deep read',category:'unexpected',meaning:b.dataset.meaning,note:'',example:'',status:'Noticed'});});
$('#responseText').addEventListener('input',e=>{$('#wordCount').textContent=`${e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0} words`});$('#saveResponse').onclick=()=>{if(!$('#responseText').value.trim())return toast('Write your response first');localStorage.setItem('marginalia-response-1',$('#responseText').value);$('#responseFeedback').hidden=false;toast('Response saved')};$('#responseText').value=localStorage.getItem('marginalia-response-1')||'';$('#responseText').dispatchEvent(new Event('input'));
